tools:
  - id: search_tools
    type: tool
    path: trip_planner.tools.search_tools.SearchTools

  - id: browser_tools
    type: tool
    path: trip_planner.tools.browser_tools.BrowserTools

  - id: calculator_tools
    type: tool
    path: trip_planner.tools.calculator_tools.CalculatorTools
