flow:
  name: Travel Planning Workflow
  description: >
    Comprehensive travel planning pipeline that selects the best city,
    gathers local insights, designs itinerary, optimizes budget, ensures safety,
    suggests packing, and consolidates final travel document.

  steps:
    - id: step_1_select_city
      name: City Selection
      agent: city_selection_expert
      task_id: identify_best_city
      inputs:
        origin: "{{origin}}"
        cities: "{{cities}}"
        date_range: "{{date_range}}"
        interests: "{{interests}}"
      outputs:
        chosen_city: city_selection_expert.output.chosen_city
        city_selection_report: city_selection_expert.output
      next_step: step_2_local_insights

    - id: step_2_local_insights
      name: Local Culture and Attractions Gathering
      agent: local_expert
      task_id: gather_city_insights
      inputs:
        chosen_city: "{{step_1_select_city.chosen_city}}"
        date_range: "{{date_range}}"
        origin: "{{origin}}"
        interests: "{{interests}}"
      outputs:
        local_guide: local_expert.output
      next_step: step_3_create_itinerary

    - id: step_3_create_itinerary
      name: Itinerary Creation
      agent: travel_concierge
      task_id: create_itinerary
      inputs:
        chosen_city: "{{step_1_select_city.chosen_city}}"
        date_range: "{{date_range}}"
        origin: "{{origin}}"
        interests: "{{interests}}"
        local_guide: "{{step_2_local_insights.local_guide}}"
      outputs:
        itinerary_markdown: travel_concierge.output
      next_step: step_4_budget_analysis

    - id: step_4_budget_analysis
      name: Budget Analysis and Optimization
      agent: budget_optimizer
      task_id: analyze_budget
      inputs:
        chosen_city: "{{step_1_select_city.chosen_city}}"
        origin: "{{origin}}"
        date_range: "{{date_range}}"
        interests: "{{interests}}"
      outputs:
        budget_report: budget_optimizer.output
      next_step: step_5_safety_evaluation

    - id: step_5_safety_evaluation
      name: Safety Advisory
      agent: safety_advisor
      task_id: evaluate_safety
      inputs:
        chosen_city: "{{step_1_select_city.chosen_city}}"
        date_range: "{{date_range}}"
      outputs:
        safety_report: safety_advisor.output
      next_step: step_6_packing_suggestions

    - id: step_6_packing_suggestions
      name: Packing List Recommendations
      agent: packing_expert
      task_id: suggest_packing_list
      inputs:
        chosen_city: "{{step_1_select_city.chosen_city}}"
        date_range: "{{date_range}}"
      outputs:
        packing_list: packing_expert.output
      next_step: step_7_finalize_itinerary

    - id: step_7_finalize_itinerary
      name: Final Itinerary Consolidation
      agent: itinerary_manager
      task_id: finalize_itinerary
      inputs:
        chosen_city: "{{step_1_select_city.chosen_city}}"
        date_range: "{{date_range}}"
        city_selection_report: "{{step_1_select_city.city_selection_report}}"
        local_guide: "{{step_2_local_insights.local_guide}}"
        itinerary_markdown: "{{step_3_create_itinerary.itinerary_markdown}}"
        budget_report: "{{step_4_budget_analysis.budget_report}}"
        safety_report: "{{step_5_safety_evaluation.safety_report}}"
        packing_list: "{{step_6_packing_suggestions.packing_list}}"
      outputs:
        final_travel_document: itinerary_manager.output
      next_step: null
